name: twist
services:
    twist-postgres:
        container_name: twist-postgres
        image: postgres:latest
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            PGPORT: 55432
        ports:
            - 55432:55432
        networks:
            - twist_default
    twist-backend:
        container_name: twist-backend
        build:
            context: .
        restart: unless-stopped
        environment:
            DATABASE_URL: ${DATABASE_URL}
            AT_SECRET: ${AT_SECRET}
            RT_SECRET: ${RT_SECRET}
        depends_on:
            - twist-postgres
        networks:
            - nginx_default
            - twist_default
networks:
    nginx_default:
        name: nginx_default
        external: true
    twist_default:
        name: twist_default
        external: true
